name: Azure Exporter Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # Determines the scheduled interval for this workflow. This example runs every 4 hours.

jobs:
  run-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Run azure Integration
        uses: port-labs/ocean-sail@v1
        with:
          type: azure
          port_client_id: ${{ secrets.PORT_CLIENT_ID }}
          port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
          port_base_url: "https://api.getport.io"
          config: |
            azure_client_id: ${{ secrets.OCEAN__SECRET__AZURE_CLIENT_ID }}
            azure_client_secret: ${{ secrets.OCEAN__SECRET__AZURE_CLIENT_SECRET }}
            azure_tenant_id: ${{ secrets.OCEAN__SECRET__AZURE_TENANT_ID }}
